version: '3.9'

services:
  backend:
    build: ./backend/
    ports:
      - 8000:8000
    container_name: backend
    env_file: ./backend/app/.env
    volumes:
      - ./backend/app:/app
    command: uvicorn index:app --reload --host 0.0.0.0 --port 8000
  
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend/app:/app:cached
    command: sh -c "npm start"

  postgresql:
    build: ./postgresql/
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: nwriter
      POSTGRES_PASSWORD: pAssword
    restart: always
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
        - 8888:80
    volumes:
        - pgadmin4_volume:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: root
        PGADMIN_DEFAULT_PASSWORD: pAssword
    depends_on:
      - postgresql

volumes:
  pgadmin4_volume:
    external: true